name: Auto Scraper System

on:
  schedule:
    - cron: '0 */6 * * *' # هيشتغل كل 6 ساعات
  workflow_dispatch: # للتشغيل اليدوي

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Scraper
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
          SAFKA_EMAIL: ${{ secrets.SAFKA_EMAIL }}
          SAFKA_PASSWORD: ${{ secrets.SAFKA_PASSWORD }}
        run: python scraper.py
